import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/common/NavBar'
import AuthProvider from './api/auth/Provider'
import { ThemeProvider } from './components/daisy/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
          <NavBar />
          <main className="px-8">{children}</main>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
